<?php
    $provincias=array(
    "Álava", 
    "Albacete", 
    "Alicante",
    "Almería",
    "Asturias",
    "Ávila", 
    "Badajoz", 
    "Barcelona", 
    "Burgos", 
    "Cáceres", 
    "Cádiz", 
    "Cantabria", 
    "Castellón", 
    "Ciudad Real", 
    "Córdoba", 
    "Cuenca", 
    "Gerona", 
    "Granada", 
    "Guadalajara", 
    "Guipúzcoa", 
    "Huelva", 
    "Huesca", 
    "Islas Baleares", 
    "Jaén", 
    "La Coruña", 
    "La Rioja", 
    "Las Palmas", 
    "León", 
    "Lérida", 
    "Lugo", 
    "Madrid", 
    "Málaga", 
    "Murcia", 
    "Navarra", 
    "Orense", 
    "Palencia", 
    "Pontevedra", 
    "Salamanca", 
    "Santa Cruz de Tenerife", 
    "Segovia", 
    "Sevilla", 
    "Soria", 
    "Tarragona", 
    "Teruel", 
    "Toledo", 
    "Valencia", 
    "Valladolid", 
    "Vizcaya", 
    "Zamora", 
    "Zaragoza");
?>